services:
  devbox:
    image: ghcr.io/ksbbs/devbox:latest
    container_name: devbox
    restart: always
    ports:
      - "127.0.0.1:${DEVBOX_SERVER_PORT:-8080}:${DEVBOX_SERVER_PORT:-8080}"
    volumes:
      - devbox-data:/data
    environment:
      - DEVBOX_SERVER_PORT=${DEVBOX_SERVER_PORT:-8080}
      - DEVBOX_AUTH_TOKEN=${AUTH_TOKEN:-}
      - DEVBOX_PUBLIC_URL=${PUBLIC_URL:-}
    command:
      - "-c"
      - "/etc/devbox/default.yaml"
      - "-f"
      - "/usr/share/devbox/frontend"

volumes:
  devbox-data: